version: '2'
services:
    myapp:
        build: .
        volumes:
            ['.:/app']
        ports:
            ['3000:3000']
        links:
            ['mongo']
    mongo:
       image: mongo:latest
       volumes:
            ['../database:/app/db']
       ports:
            ['27017:27017']
